### ISSUE TITLE
USDView, USDZip don't work out of the box. v0.6

### ISSUE THREAD

**Issue by ansuter** [Autodesk/maya-usd#1058]
**Describe the bug**
Launching USDView or USDZip from MayaUSD folder results in failure. USDView complains about shiboken2 and USDZip complains about _ar.

USDView:
``` 
>usdview
PySide2/__init__.py: Unable to import shiboken2 from C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\bin, C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib, C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python, C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\bin, C:\Program Files\Autodesk\Maya2021\Python37\Lib\site-packages, C:\Users\ansuter, C:\python379\python37.zip, C:\python379\DLLs, C:\python379\lib, C:\python379, C:\Users\ansuter\AppData\Roaming\Python\Python37\site-packages, C:\python379\lib\site-packages
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python\pxr\Usdviewq\__init__.py", line 29, in <module>
    from .qt import QtWidgets, QtCore
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python\pxr\Usdviewq\qt.py", line 42, in <module>
    PySideModule = GetPySideModule()
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python\pxr\Usdviewq\qt.py", line 31, in GetPySideModule
    from . import attributeValueEditorUI
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python\pxr\Usdviewq\attributeValueEditorUI.py", line 11, in <module>
    from PySide2 import QtCore, QtGui, QtWidgets
  File "C:\Program Files\Autodesk\Maya2021\Python37\Lib\site-packages\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Program Files\Autodesk\Maya2021\Python37\Lib\site-packages\PySide2\__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "C:\Program Files\Autodesk\Maya2021\Python37\Lib\site-packages\shiboken2\__init__.py", line 27, in <module>
    from .shiboken2 import *
ImportError: DLL load failed: The specified module could not be found.
```
USDZip
```
>usdzip
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\bin\usdzip", line 31, in <module>
    from pxr import Ar, Sdf, Tf, Usd, UsdUtils
  File "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\lib\python\pxr\Ar\__init__.py", line 24, in <module>
    from . import _ar
ImportError: DLL load failed: The specified module could not be found.
```

**Steps to reproduce**
Set windows path to allow usdview/usdzip 

![image](https://user-images.githubusercontent.com/16786318/104223009-ee00f600-53f7-11eb-883a-ab121aa714fa.png)
Try running USDView or USDZip

**Expected behavior**
I would expect that USDView or USDZip have all dependencies available, and if pathed properly it would launch them. Using my own built version of usd, and setting the same paths to that folder results in usdview and usdzip working.

**Specs (if applicable):**
Windows 10
Maya Version: PR121
MayaUSD: 0.6.0_202012102328-efea2cd

**Comment by seando-adsk** [comment]
@ansuter In order to run these USD tools, you need to set **PATH** and **PYTHONPATH**. Is that what you did?

1. To **PATH** add: _...\mayausd\USD3\bin;...\mayausd\USD3\lib_
2. To **PYTHONPATH** add: _...\mayausd\USD3\lib\python_

**Comment by ansuter** [comment]
Hi there,

So oddly enough, I did usdzip working finally. My paths seemed fine. I think the only difference I had was \mayausd\USD3\lib\python was also in my PATH, not just in PYTHONPATH. 

USDView still gives me the above error.

**Comment by seando-adsk** [comment]
From the _usdview_ output above I see that it is trying to load some python modules from the MayaPR121. This version of Maya is **dual-python** and thus is a little more complicated to use by setting PATH/PYTHONPATH yourself. An easier way would be to use mayapy to run usdview. You will need to install PyOpenGL. 

Just add the USD bin/lib to your PATH and USD lib/python to your PYTHONPATH. Then run these lines:
`mayapy -m pip install PyOpenGL==3.1.0`
`mayapy "C:\Program Files\Autodesk\MayaUSD\Maya2021\0.6.0_202012102328-efea2cd\mayausd\USD3\bin\usdview"`

**Comment by ansuter** [comment]
Great, switching to mayapy in this case appears to work. Thank you.

**Comment by BigRoy** [comment]
This topic also came up on [Maya Programming forums where I also presented an example of how it could be used](https://forums.autodesk.com/t5/maya-programming/maya-usd-usdview/m-p/10255710).
