### ISSUE TITLE
maya usd build failed

### ISSUE THREAD

**Issue by wandth** [Autodesk/maya-usd#2306]
**Describe the issue**
Build Maya-dev  gbk decode error `illegal multibyte sequence`

build command
```bash
>python build.py --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location="D:\usd_compile\usd" --devkit-location="C:\Program Files\Autodesk\Autodesk_Maya_2020_4_Update_DEVKIT_Windows\devkitBase" --qt-location="D:\Qt\5.12.5\msvc2017_64"  --build-args="-DBUILD_ADSK_PLUGIN=ON,-DBUILD_PXR_PLUGIN=ON,-DBUILD_TESTS=ON" "D:\usd_compile\maya-usd"
```
**build.log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/8539859/build_log.txt)

**error**
![image](https://user-images.githubusercontent.com/34237282/164683007-78b0ad03-57b7-46bd-bf8a-f0f9a600beee.png)
```bash
Traceback (most recent call last):
  File "build.py", line 602, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 371, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 277, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 146, in Run
    l = p.stdout.readline().decode(encoding)
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 24-25: illegal multibyte sequence
```

**Specs:**
 - OS & version : windows 11
 - Compiler & version : visual studio 2017
 - Maya version : maya 2020.4
 - Maya USD commit SHA : maya-dev  932483b17418265599c4ae33ad8531e79d991abb failed
 - Pixar USD commit SHA: USD-22.03

Then I debug the error line, It minght because of Chinese language

![image](https://user-images.githubusercontent.com/34237282/164686807-d1377920-09da-4605-808d-81c6b3fdf6c6.png)

if I change the decode to "utf8" 
![image](https://user-images.githubusercontent.com/34237282/164705264-a9c19496-830a-47a5-ad8d-de81f13eb3d3.png)
it is his build log
[build_log.txt](https://github.com/Autodesk/maya-usd/files/8540518/build_log.txt)
what I changed
![image](https://user-images.githubusercontent.com/34237282/164705494-b2bf7154-15ba-406c-b922-3654ea7874ba.png)

**Comment by wandth** [comment]
![image](https://user-images.githubusercontent.com/34237282/164708838-c2fe964f-52ce-4d63-8467-368b9fbe54e0.png)
I change the code to that， it build successful
