### ISSUE TITLE
Could NOT find Boost  (found version "1.65.1")

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#235]
Hi! 
I am pretty new in here, not sure what I am doing wrong. 
I managed to install USD (20.02) plugin successfully with VS 2017

> python build_scripts\build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --materialx  "C:\USD" 

but maya plugin (dev branch) for some reason won't install. Could somone point me to right direction? I am missing something?

here is the log:

```
c:\maya-usd>python build.py --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location C:\USD --devkit-location C:\mayadev --install-location C:\MayaUSD --build-args="-DBUILD_ADSK_PLUGIN=ON,-DBUILD_PXR_PLUGIN=OFF,-DBUILD_TESTS=OFF" C:\mayaworkspace

    Building with settings:
      Source directory          c:\maya-usd
      Workspace directory       C:\mayaworkspace
      Build directory           C:\mayaworkspace\build\RelWithDebInfo
      Install directory         C:\MayaUSD
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 C:\mayaworkspace\build\RelWithDebInfo\build_log.txt
      Build arguments           ['-DBUILD_ADSK_PLUGIN=ON', '-DBUILD_PXR_PLUGIN=OFF', '-DBUILD_TESTS=OFF']
      Stages arguments          ['clean', 'configure', 'build', 'install']
#####################################################################################
log date: 2020-01-31 20:30
commit sha: d2c1a4628de9d659746b8850e28a9d6d6c7d8d69
commit date: Fri Jan 31 10:03:47 2020 -0500
#####################################################################################

cmake -DCMAKE_INSTALL_PREFIX="C:\MayaUSD" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2020" -DPXR_USD_LOCATION="C:\USD" -DMAYA_DEVKIT_LOCATION="C:\mayadev" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF -DBUILD_ADSK_PLUGIN=ON -DBUILD_PXR_PLUGIN=OFF -DBUILD_TESTS=OFF "c:\maya-usd"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.16.27035.0
-- The CXX compiler identification is MSVC 19.16.27035.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: C:/Python27/python.exe (found suitable exact version "2.7.14") found components: Interpreter
-- _PYTHON_VERSION_LIST: 2.7.14.final.0
-- PYTHON_PREFIX: C:\Python27
-- PYTHON_INCLUDE_DIR: C:\Python27\include
-- PYTHON_SITE_PACKAGES: C:\Python27\Lib\site-packages
-- PYTHON_MODULE_EXTENSION: .pyd
-- PYTHON_IS_DEBUG: 0
-- PYTHON_SIZEOF_VOID_P: 8
-- PYTHON_LIBRARY_SUFFIX: 27
-- PYTHON_LIBDIR:
-- PYTHON_MULTIARCH:
-- Found PythonLibs: C:/Python27/libs/Python27.lib
-- Building with Python:
--    PYTHON_INCLUDE_DIRS = C:/Python27/include
--    PYTHON_LIBRARIES    = C:/Python27/libs/Python27.lib
--    Python_EXECUTABLE   = C:/Python27/python.exe
-- Found Maya: C:/Program Files/Autodesk/Maya2020/bin/maya.exe (found version "20200000")
-- USD include dir: C:/USD/include
-- USD library dir: C:/USD/lib
-- USD version: 0.20.2
-- Found USD: C:\USD (found version "0.20.2")
Updated PYTHONPATH: C:\USD\lib\python;C:\USD\lib\python
Updated PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\7-Zip;C:\Program Files\NASM;C:\USD\bin;C:\USD\lib;C:\Ninja;C:\Program Files\Git\cmd;C:\Users\dawid\AppData\Local\Microsoft\WindowsApps;C:\Users\dawid\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\USD\bin;C:\USD\lib
-- UFE include dir: C:/mayadev/devkit/ufe/include
-- UFE library: C:/mayadev/devkit/ufe/lib/ufe_1.lib
-- UFE version: 1.0.0
-- Building with UFE 1.0.0 features enabled.
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: filesystem) (found version "1.65.1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  lib/CMakeLists.txt:37 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/mayaworkspace/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):
  File "build.py", line 580, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 357, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 263, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 156, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\MayaUSD" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2020" -DPXR_USD_LOCATION="C:\USD" -DMAYA_DEVKIT_LOCATION="C:\mayadev" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF -DBUILD_ADSK_PLUGIN=ON -DBUILD_PXR_PLUGIN=OFF -DBUILD_TESTS=OFF "c:\maya-usd"'
See C:\mayaworkspace\build\RelWithDebInfo\build_log.txt for more details.`
```

**Comment by Xaia** [comment]
I was using USD 20.02 instead of 19.11

**Comment by fabiaserra** [comment]
I came across the same error with 20.02 and the problem was that I had to rebuild USD again with:

`python build_scripts\build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --materialx "C:\dev\usd\build"`

First time I ran it without the `--build-args boost` and the second time I ran it with it it I still got the error but removing my `build` folder and rebuilding did the trick
