### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect: 'C:'

### ISSUE THREAD

**Issue by hamedsabri** [Autodesk/maya-usd#2911]
**Describe the issue**

Hi guys, I have built MayaUSD(0.22.0) with USD(21.11) with Python 3.10.8 on Windows. Both mayaUsdPlugin and pxrUsd plugins load fine without any issues but having problems running the python tests. Is this related to the python version I am using?

Thanks,
-H

**Log**
```
C:\Users\hamed\Desktop\workspace2\build\RelWithDebInfo>ctest -R testPrimWriter -VV

UpdateCTestConfiguration  from :C:/workspace/build/RelWithDebInfo/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/workspace/build/RelWithDebInfo/DartConfiguration.tcl
Test project C:/workspace/build/RelWithDebInfo
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 57
    Start 57: testPrimWriter

57: Test command: "C:\Program Files\Autodesk\Maya2024\bin\mayapy.exe" "C:/workspace/build/RelWithDebInfo/test/Temporary/scripts/runner_testPrimWriter.py"
57: Working Directory: C:/workspace/build/RelWithDebInfo/test/lib/mayaUsd/fileio
57: Environment variables:
57:  MAYA_MODULE_PATH=
57:  PATH=C:/workspace/install/RelWithDebInfo/lib/gtest;C:\Program Files\Autodesk\Maya2024/bin;C:/workspace/install/RelWithDebInfo/lib;C:/workspace/install/RelWithDebInfo/plugin/pxr/maya/lib;C:/workspace/install/RelWithDebInfo/plugin/al/lib;C:/USDRel/bin;C:/USDRel/lib;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools;C:\Python310\Scripts;C:\Python310;C:\Program Files (x86)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt;C:\Program Files (x86)\Intel\oneAPI\tbb\latest\redist\ia32\vc_mt;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\intel64_win\compiler;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\ia32_win\compiler;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Sublime Text;C:\Program Files\Graphviz\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Users\hamed\AppData\Local\Microsoft\WindowsApps;C:\Users\hamed\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\GnuWin32\bin;C:\ProgramData\chocolatey\lib\winflexbison3\tools;C:;C:\USDRel\bin;C:\USDRel\lib
57:  PYTHONPATH=C:/workspace/install/RelWithDebInfo/lib/scripts;C:/workspace/install/RelWithDebInfo/lib/python;C:/workspace/install/RelWithDebInfo/plugin/adsk/scripts;C:/workspace/install/RelWithDebInfo/plugin/pxr/lib/python;C:/workspace/install/RelWithDebInfo/plugin/al/lib/python;C:/Users/hamed/Github/maya-usd/test/testUtils;C:/Users/hamed/Github/maya-usd/test/lib/mayaUsd/fileio;C:/USDRel/lib/python;C:\USDRel\lib\python
57:  MAYA_PLUG_IN_PATH=C:/workspace/install/RelWithDebInfo/plugin/adsk/plugin;C:/workspace/install/RelWithDebInfo/plugin/pxr/maya/plugin;C:/workspace/install/RelWithDebInfo/plugin/al/plugin
57:  MAYA_SCRIPT_PATH=C:/workspace/install/RelWithDebInfo/lib/scripts;C:/workspace/install/RelWithDebInfo/plugin/adsk/scripts;C:/workspace/install/RelWithDebInfo/plugin/pxr/maya/lib/usd/usdMaya/resources
57:  XBMLANGPATH=C:/workspace/install/RelWithDebInfo/lib/icons
57:  PXR_PLUGINPATH_NAME=C:/workspace/install/RelWithDebInfo/lib/usd;C:/workspace/install/RelWithDebInfo/plugin/pxr/lib/usd;C:/workspace/install/RelWithDebInfo/plugin/al/lib/usd;C:/workspace/install/RelWithDebInfo/plugin/al/plugin
57:  PXR_MTLX_STDLIB_SEARCH_PATHS=C:/USDRel/libraries;C:/workspace/install/RelWithDebInfo/libraries
57:  UFE_PREVIEW_VERSION_NUM=4045
57:  TMP=C:/workspace/build/RelWithDebInfo/test/Temporary/testPrimWriter
57:  TEMP=C:/workspace/build/RelWithDebInfo/test/Temporary/testPrimWriter
57:  MAYA_APP_DIR=C:/workspace/build/RelWithDebInfo/test/Temporary/testPrimWriter
57:  MAYA_PYTHON_VERSION=3
57:  MAYA_NO_STANDALONE_ATEXIT=1
57:  MAYA_DEBUG_ENABLE_CRASH_REPORTING=1
57:  MAYA_DEBUG_NO_SAVE_ON_CRASH=1
57:  MAYA_NO_MORE_ASSERT=1
57:  MAYA_DISABLE_CIP=1
57:  MAYA_DISABLE_CER=1
57:  MAYA_IGNORE_DIALOGS=1
57: Test timeout computed to be: 10000000
57: MAYA_DEBUG_NO_SAVE_ON_CRASH is set.
57: Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
57: Traceback (most recent call last):
57:   File "C:\Users\hamed\Desktop\workspace2\build\RelWithDebInfo\test\Temporary\scripts\runner_testPrimWriter.py", line 8, in <module>
57:     import testPrimWriter
57:   File "C:\Users\hamed\Github\maya-usd\test\lib\mayaUsd\fileio\testPrimWriter.py", line 18, in <module>
57:     import mayaUsd.lib as mayaUsdLib
57:   File "C:\Users\hamed\Desktop\workspace2\install\RelWithDebInfo\lib\python\mayaUsd\lib\__init__.py", line 1, in <module>
57:     from pxr import Tf
57:   File "c:\usdrel\lib\python\pxr\Tf\__init__.py", line 163, in <module>
57:     PreparePythonModule()
57:   File "c:\usdrel\lib\python\pxr\Tf\__init__.py", line 87, in PreparePythonModule
57:     with WindowsImportWrapper():
57:   File "C:\Program Files\Autodesk\Maya2024\Python\lib\contextlib.py", line 135, in __enter__
57:     return next(self.gen)
57:   File "c:\usdrel\lib\python\pxr\Tf\__init__.py", line 47, in WindowsImportWrapper
57:     dirs.append(os.add_dll_directory(path))
57:   File "C:\Program Files\Autodesk\Maya2024\Python\lib\os.py", line 1118, in add_dll_directory
57:     cookie = nt._add_dll_directory(path)
57: OSError: [WinError 87] The parameter is incorrect: 'C:'
1/1 Test #57: testPrimWriter ...................***Failed    6.72 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
fileio    =   6.72 sec*proc (1 test)

Total Test time (real) =   7.62 sec

The following tests FAILED:
         57 - testPrimWriter (Failed)
Errors while running CTest
```

**Specs:**
 - OS & version [e.g. Windows 10]
 - Compiler & version [e.g. VS 2017]
 - Maya version [e.g. Maya 2023 PR 142]
 - Maya USD commit SHA [e.g. dev at b3fb7006]
 - Pixar USD commit SHA [e.g. 21.11]

**Comment by indigo3d** [comment]
> PATH=...;C:\ProgramData\chocolatey\lib\winflexbison3\tools;C:;C:\USDRel\bin;C:\USDRel\lib

I think the environment `PATH` has wrong value `C:`
Remove that may help.
