### ISSUE TITLE
Crash when trying to assign file path to image node in LookdevX

### ISSUE THREAD

**Issue by dtoshevcg** [Autodesk/maya-usd#3662]
**Describe the bug**

Maya crashes when trying to open the file picker from LookdevX to choose a file for an ND_image node using Maya USD 0.27.0

**Steps to reproduce**
1. Open a new scene.
2. Create a new USD Stage.
3. Create a plane > Right-click > Duplicate to USD Stage. Delete or hide the original Maya plane.
4. Right-click on the plane > Assign new material > MaterialX > Standard Surface.
5. Right-click on the plane > Show in lookdevX.
6. Open up the shader and add a tiledimage node or image node (ND_tiledimage, ND_image materialx node).
7. Click the file loading icon. Maya will crash.

**Expected behavior**
No crash

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - OS & version [e.g. Windows 10]
 Arch Linux; Rocky 8.
 - Compiler & version [e.g. gcc 11.2.1]
 - Maya version [e.g. Maya 2024]
 Maya 2024
 - Maya USD commit SHA [e.g. dev at caa921c1]
 0.27.0 release
 - Pixar USD commit SHA [e.g. dev at b85ddac2]

**Additional context**
Backtrace from GDB:
```
(gdb) bt
#0  0x0000000028a7aa20 in ?? ()
#1  0x00007ff398c0bf92 in MayaUsd_v0::ufe::UsdAttributeHolder::hasMetadata(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /usr/autodesk/mayausd/maya2024/0.27.0_202402071410-bf4bd3e/mayausd/MayaUSD/plugin/adsk/plugin/../../../lib/libmayaUsd.so
#2  0x00007ff398c8d623 in MayaUsd_v0::ufe::UsdShaderAttributeHolder::hasMetadata(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /usr/autodesk/mayausd/maya2024/0.27.0_202402071410-bf4bd3e/mayausd/MayaUSD/plugin/adsk/plugin/../../../lib/libmayaUsd.so
#3  0x00007ff3c4908659 in LookdevXUsd::UsdFileHandler::openFileDialog[abi:cxx11](std::shared_ptr<Ufe_v4::AttributeFilename> const&) const () from /usr/autodesk/lookdevx/maya2024/1.2.0/plug-ins/lookdevx/plug-ins/LookdevXMaya.so
#4  0x00007ff3c49e21d7 in ?? () from /usr/autodesk/lookdevx/maya2024/1.2.0/plug-ins/lookdevx/plug-ins/LookdevXMaya.so
#5  0x00007ff5526e0f1d in void doActivate<false>(QObject*, int, void**) () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#6  0x00007ff553c539bd in QAbstractButtonPrivate::emitPressed() () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#7  0x00007ff553c54295 in QAbstractButton::mousePressEvent(QMouseEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#8  0x00007ff553ba662e in QWidget::event(QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#9  0x00007ff553b67a7f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#10 0x00007ff553b6ef29 in QApplication::notify(QObject*, QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#11 0x00007ff555f040bd in ?? () from /usr/autodesk/maya2024//lib/libExtensionLayer.so
#12 0x00007ff5526accfa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#13 0x00007ff553b6dac0 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#14 0x00007ff553bbead8 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#15 0x00007ff553bc1ad5 in QWidgetWindow::event(QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#16 0x00007ff553b67a7f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Widgets.so.5
#17 0x00007ff555f040bd in ?? () from /usr/autodesk/maya2024//lib/libExtensionLayer.so
#18 0x00007ff5526accfa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#19 0x00007ff552b315e7 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/autodesk/maya2024//lib/libQt5Gui.so.5
#20 0x00007ff552b08e9c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/autodesk/maya2024//lib/libQt5Gui.so.5
#21 0x00007ff5361169ba in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /usr/autodesk/maya2024//lib/libQt5XcbQpa.so.5
#22 0x00007ff54900fa31 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#23 0x00007ff54906ccc9 in ?? () from /usr/lib/libglib-2.0.so.0
#24 0x00007ff54900d0e2 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#25 0x00007ff5527008c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#26 0x00007ff5526ab88b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#27 0x00007ff5526b34cc in QCoreApplication::exec() () from /usr/autodesk/maya2024//lib/libQt5Core.so.5
#28 0x00007ff555eff324 in Tapplication::start() () from /usr/autodesk/maya2024//lib/libExtensionLayer.so
#29 0x000000000041a3fb in appmain() ()
#30 0x0000000000415500 in main ()
```

**Comment by wallworm** [comment]
Thanks for reporting this. We will look into it.
